import { buildElement } from "./build";

/**
 * Maps key of {@link JSX.IntrinsicElements} completely, but some keys are omitted due to reasons below:
 * 1. Deprecated: These tags are deprecated in HTML5 standards. See {@link HTMLElementDeprecatedTagNameMap}
 * 2. Unreachable: These tags are unable to reach in React applications, or have no interaction with {@link FlexiveProps}.
 * 3. React-only: These tags are only used in native React context such as electron.
 *
 */

// TODO: Add non-displayed tags to unreachables
export const A = buildElement("a");
export const Abbr = buildElement("abbr");
export const Address = buildElement("address");
export const Area = buildElement("area");
export const Article = buildElement("article");
export const Aside = buildElement("aside");
export const Audio = buildElement("audio");
export const B = buildElement("b");
export const Base = buildElement("base");
export const Bdi = buildElement("bdi");
export const Bdo = buildElement("bdo");
// export const Big = buildElement("big"); Deprecated
export const Blockquote = buildElement("blockquote");
// export const Body = buildElement("body"); Unreachable
export const Br = buildElement("br");
export const Button = buildElement("button");
export const Canvas = buildElement("canvas");
export const Caption = buildElement("caption");
// export const Center = buildElement("center"); Deprecated
export const Cite = buildElement("cite");
export const Code = buildElement("code");
export const Col = buildElement("col");
export const Colgroup = buildElement("colgroup");
export const Data = buildElement("data");
export const Datalist = buildElement("datalist");
export const Dd = buildElement("dd");
export const Del = buildElement("del");
export const Details = buildElement("details");
export const Dfn = buildElement("dfn");
export const Dialog = buildElement("dialog");
export const Div = buildElement("div");
export const Dl = buildElement("dl");
export const Dt = buildElement("dt");
export const Em = buildElement("em");
export const Embed = buildElement("embed");
export const Fieldset = buildElement("fieldset");
export const Figcaption = buildElement("figcaption");
export const Figure = buildElement("figure");
export const Footer = buildElement("footer");
export const Form = buildElement("form");
export const H1 = buildElement("h1");
export const H2 = buildElement("h2");
export const H3 = buildElement("h3");
export const H4 = buildElement("h4");
export const H5 = buildElement("h5");
export const H6 = buildElement("h6");
// export const Head = buildElement("head"); Unreachable
export const Header = buildElement("header");
export const Hgroup = buildElement("hgroup");
export const Hr = buildElement("hr");
// export const Html = buildElement("html"); Unreachable
export const I = buildElement("i");
export const Iframe = buildElement("iframe");
export const Img = buildElement("img");
export const Input = buildElement("input");
export const Ins = buildElement("ins");
export const Kbd = buildElement("kbd");
// export const Keygen = buildElement("keygen"); Deprecated
export const Label = buildElement("label");
export const Legend = buildElement("legend");
export const Li = buildElement("li");
export const Link = buildElement("link");
export const Main = buildElement("main");
export const Map = buildElement("map");
export const Mark = buildElement("mark");
export const Menu = buildElement("menu");
// export const Menuitem = buildElement("menuitem"); Deprecated
export const Meta = buildElement("meta");
export const Meter = buildElement("meter");
export const Nav = buildElement("nav");
// export const Noindex = buildElement("noindex"); Deprecated
export const Noscript = buildElement("noscript");
export const Object = buildElement("object");
export const Ol = buildElement("ol");
export const Optgroup = buildElement("optgroup");
export const Option = buildElement("option");
export const Output = buildElement("output");
export const P = buildElement("p");
// export const Param = buildElement("param");
export const Picture = buildElement("picture");
export const Pre = buildElement("pre");
export const Progress = buildElement("progress");
export const Q = buildElement("q");
export const Rp = buildElement("rp");
export const Rt = buildElement("rt");
export const Ruby = buildElement("ruby");
export const S = buildElement("s");
export const Samp = buildElement("samp");
export const Search = buildElement("search");
export const Slot = buildElement("slot");
// export const Script = buildElement("script"); // Unreachable
export const Section = buildElement("section");
export const Select = buildElement("select");
export const Small = buildElement("small");
export const Source = buildElement("source");
export const Span = buildElement("span");
export const Strong = buildElement("strong");
// export const Style = buildElement("style"); // Unreachable
export const Sub = buildElement("sub");
export const Summary = buildElement("summary");
export const Sup = buildElement("sup");
export const Table = buildElement("table");
export const Template = buildElement("template");
export const Tbody = buildElement("tbody");
export const Td = buildElement("td");
export const Textarea = buildElement("textarea");
export const Tfoot = buildElement("tfoot");
export const Th = buildElement("th");
export const Thead = buildElement("thead");
export const Time = buildElement("time");
export const Title = buildElement("title");
export const Tr = buildElement("tr");
export const Track = buildElement("track");
export const U = buildElement("u");
export const Ul = buildElement("ul");
export const Var = buildElement("var");
export const Video = buildElement("video");
export const Wbr = buildElement("wbr");
// export const Webview = buildElement("webview"); // React-only
