import { CSSProperties, useMemo } from "react";
import { LayoutStyle, parseLayoutStyle } from "./layoutStyle";

export const useLayoutStyle = ({
  inline,
  inlineFlex,
  block,
  grow,
  shrink,
  basis,
  colReverse,
  row,
  rowReverse,
  wrap,
  wrapReverse,
  nowrap,
  mainAlign,
  crossAlign,
  mainSelf,
  crossSelf,
  mainSize,
  mainMax,
  mainMin,
  crossSize,
  crossMax,
  crossMin,
  p,
  m,
  g,
  mainOver,
  crossOver,
  style: styleOverride,
}: LayoutStyle & { style?: CSSProperties }): CSSProperties => {
  const style = useMemo(
    () =>
      parseLayoutStyle({
        inline,
        inlineFlex,
        block,
        grow,
        shrink,
        basis,
        colReverse,
        row,
        rowReverse,
        wrap,
        wrapReverse,
        nowrap,
        mainAlign,
        crossAlign,
        mainSelf,
        crossSelf,
        mainSize,
        mainMax,
        mainMin,
        crossSize,
        crossMax,
        crossMin,
        p,
        m,
        g,
        mainOver,
        crossOver,
        ...styleOverride,
      }),
    [
      inline,
      inlineFlex,
      block,
      grow,
      shrink,
      basis,
      colReverse,
      row,
      rowReverse,
      wrap,
      wrapReverse,
      nowrap,
      mainAlign,
      crossAlign,
      mainSelf,
      crossSelf,
      mainSize,
      mainMax,
      mainMin,
      crossSize,
      crossMax,
      crossMin,
      p,
      m,
      g,
      mainOver,
      crossOver,
      styleOverride,
    ],
  );

  return style;
};
